spring:
  application:
    name: api-gateway

server:
  port: 8090

jwt:
#  base64 encoded user:123456
  secret: dXNlcjoxMjM0NTY=

services:
  orders:
    url: http://localhost:8091
  products:
    url: http://localhost:8092
