openapi: 3.0.3

info:
  title: Product API
  version: 1.0.4

paths:
  /products:
    get:
      summary: Get all products
      operationId: getProducts
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/components.yaml#/components/schemas/ProductResponse'

    post:
      summary: Add a single product
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/components.yaml#/components/schemas/ProductRequest'
      responses:
        '201':
          description: Product created
        '401':
          description: Unauthorized
        '409':
          description: Duplicate product

  /products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: './schemas/components.yaml#/components/schemas/ProductResponse'
        '404':
          description: Product not found

    put:
      summary: Update product price
      operationId: updateProductPrice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: number
              format: double
      responses:
        '200':
          description: Product updated
        '401':
          description: Unauthorized
        '404':
          description: Product not found

  /products/add:
    post:
      summary: Bulk add products
      operationId: addProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/components.yaml#/components/schemas/BulkProductRequest'
      responses:
        '200':
          description: Products added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/components.yaml#/components/schemas/ProductResponse'
