#feign:
#  name: feign-client
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#
#  autoconfiguration:
#    jackson:
#      enabled: true